def getFlag(text):
        match text:
                case "DEN":
                        return ":flag_dk:"
                case "INA":
                        return ":flag_id:"
                case "THA":
                        return ":flag_th:"
                case "JPN":
                        return ":flag_jp:"
                case "SGP":
                        return ":flag_sg:"
                case "CHN":
                        return ":flag_cn:"
                case "TPE":
                        return ":flag_tw:"
                case "IND":
                        return ":flag_in:"
                case "MAS":
                        return ":flag_my:"
                case "HKG":
                        return ":flag_hk:"
                case "ENG":
                        return ":england:"
                case "CAN":
                        return ":flag_ca:"
                case "FRA":
                        return ":flag_fr:"
                case "IRL":
                        return ":flag_ie:"
                case "GUA":
                        return ":flag_gt:"
                case "ISR":
                        return ":flag_il:"
                case "NED":
                        return ":flag_nl:"
                case "KOR":
                        return ":flag_kr:"
                case "CZE":
                        return ":flag_cz:"
                case "BRA":
                        return ":flag_br:"
                case "ESP":
                        return ":flag_es:"
                case "ESA":
                        return ":flag_sv:"
                case "GER":
                        return ":flag_de:"
                case "FIN":
                        return ":flag_fi:"
                case "BEL":
                        return ":flag_be:"
                case "AZE":
                        return ":flag_az:"
                case "SWE":
                        return ":flag_se:"
                case "JOR":
                        return ":flag_jo:"
                case "POR":
                        return ":flag_pt:"
                case "KAZ":
                        return ":flag_kz:"
                case "UKR":
                        return ":flag_ua:"
                case "AUT":
                        return ":flag_at:"
                case "USA":
                        return ":flag_us:"
                case "ITA":
                        return ":flag_it:"
                case "MRI":
                        return ":flag_mu:"
                case "NGR":
                        return ":flag_ng:"
                case "SRI":
                        return ":flag_lk:"
                case "VIE":
                        return ":flag_vn:"
                case "SVK":
                        return ":flag_sk:"
                case "AUS":
                        return ":flag_au:"
                case "MEX":
                        return ":flag_mx:"
                case "EGY":
                        return ":flag_eg:"
                case "SUI":
                        return ":flag_ch:"
                case "MEX":
                        return ":flag_mx:"
                case "MEX":
                        return ":flag_mx:"
                case "BUL":
                        return ":flag_bg:"
                case "SCO":
                        return ":scotland:"
                case "ALG":
                        return ":flag_dz:"
                case "PHI":
                        return ":flag_ph:"
                case "SRB":
                        return ":flag_rs:"
                case "SLO":
                        return ":flag_si:"
                case "RSA":
                        return ":flag_za:"
                case "MDV":
                        return ":flag_mv:"
                case "PER":
                        return ":flag_pe:"
                case "NZL":
                        return ":flag_nz:"
                case "MYA":
                        return ":flag_mm:"
                case "TUR":
                        return ":flag_tr:"
                case "HUN":
                        return ":flag_hu:"
                case "NOR":
                        return ":flag_no:"
                case "POL":
                        return ":flag_pl:"
                case "EST":
                        return ":flag_ee:"
                        
        return text # in case of fall through (country code is not mapped to a flag emoji), then return the country code instead